/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : types.h
**     Project   : ProcessorExpert
**     Processor : MK60N512LQ100
**     Component : USB_OTG_STACK
**     Version   : Driver 01.00, CPU db: 3.00.001
**     Compiler  : CodeWarrior ARM C Compiler
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/

#ifndef __types_h__
#define __types_h__

#include "usbprv.h"
#include "usb_psptypes.h"
/* forward declarations */
struct dev_instance;
struct usb_interface_descriptor;
struct pipe_descriptor_struct;
struct pipe_tr_struct;
#define USB_PACKET_SIZE  uint_16
#endif

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
