/** ###################################################################
**     THIS USER MODULE IS GENERATED BY THE TOOL. MODIFY IT FOLLOW COMMENTS BELOW.
**     Filename  : usb_classes.h
**     Project   : ProcessorExpert
**     Processor : MK40N512LQ100
**     Component : USB_HOST_STACK
**     Version   : Driver 01.00, CPU db: 3.00.001
**     Compiler  : CodeWarrior ARM C Compiler
**     Date/Time : 2013-01-28, 16:49, # CodeGen: 2
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/
#ifndef __usb_classes_h__
#define __usb_classes_h__
/* End of header definition, DO NOT MODIFY LINES ABOVE */
/* Write your own includes here ...*/
#include "usb_host_cdc.h"
/* DO NOT MODIFY LINES BELOW */
typedef struct {
    GENERAL_CLASS                             G;
/* End <struct_begin_1>, DO NOT MODIFY LINES ABOVE */
/* Write your own fields of struct 1 below */
	/* Higher level callback and parameter */
	tr_callback                               USER_CALLBACK;
	pointer                                   USER_PARAM;
	uint_8                                    IFNUM;
    USB_CDC_DESC_ACM_PTR                      acm_desc;
    USB_CDC_DESC_CM_PTR                       cm_desc;
    USB_CDC_DESC_HEADER_PTR                   header_desc;
    USB_CDC_DESC_UNION_PTR                    union_desc;
   
    USB_CDC_UART_CODING                       uart_coding;

    _usb_pipe_handle                          interrupt_pipe;
    USB_CDC_ACM_STATE                         interrupt_buffer;
    
    USB_CDC_CTRL_STATE                        ctrl_state;

#define USB_ACM_DETACH           0x01
#define USB_ACM_CTRL_PIPE_FREE   0x02
#define USB_ACM_INT_PIPE_FREE    0x04

    USB_EVENT_STRUCT                            acm_event;
/* Begin of <struct_end_1>, DO NOT MODIFY LINES BELOW */
} USB_CLASS_ACM_INTF_STRUCT, _PTR_ USB_CLASS_ACM_INTF_STRUCT_PTR;
/* DO NOT MODIFY LINES ABOVE*/

/* DO NOT MODIFY LINES BELOW */
typedef struct {
    GENERAL_CLASS                             G;
/* End <struct_begin_2>, DO NOT MODIFY LINES ABOVE */
/* Write your own fields of struct 2 below */
    /* Address of bound control interface */
    /* Higher level callback and parameter */
	tr_callback                               USER_CALLBACK;
	pointer                                  USER_PARAM;

	uint_8                                    IFNUM;
    CLASS_CALL_STRUCT_PTR                     BOUND_CONTROL_INTERFACE;

    char_ptr                                  RX_BUFFER;
    char_ptr                                  RX_BUFFER_DRV;
    char_ptr                                  RX_BUFFER_APP;
    uint_32                                   RX_BUFFER_SIZE;
    uint_32                                   RX_READ;
    
    uint_32                                   TX_SENT;

    _usb_pipe_handle                          in_pipe;
    _usb_pipe_handle                          out_pipe;
   
    char_ptr                                  device_name;

#define USB_DATA_DETACH            0x01
#define USB_DATA_READ_COMPLETE     0x02
#define USB_DATA_READ_PIPE_FREE    0x04
#define USB_DATA_SEND_COMPLETE     0x08
#define USB_DATA_SEND_PIPE_FREE    0x10
    USB_EVENT_STRUCT                            data_event;
/* Begin of <struct_end_2>, DO NOT MODIFY LINES BELOW */
} USB_CLASS_DATA_INTF_STRUCT, _PTR_ USB_CLASS_DATA_INTF_STRUCT_PTR;
/* DO NOT MODIFY LINES ABOVE*/

/* Begin of <fuction_prototype>, DO NOT MODIFY LINES BELOW */
extern void usb_class_ACM_init(PIPE_BUNDLE_STRUCT_PTR, CLASS_CALL_STRUCT_PTR);
extern void usb_class_DATA_init(PIPE_BUNDLE_STRUCT_PTR, CLASS_CALL_STRUCT_PTR);
/* End <fuction_prototype>, DO NOT MODIFY LINES ABOVE */

#endif
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/

