/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : task_template_list.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Version     : Component 01.083, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-01-02, 13:43, # CodeGen: 119
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#ifndef __task_template_list_h__
#define __task_template_list_h__

/* MQX Lite task IDs */
#define APP_TASK_TASK        1U
#define KHCI_TASK_TASK       2U

/* MQX Lite task stack sizes */
#define APP_TASK_TASK_STACK_SIZE (sizeof(TD_STRUCT) + 800 + PSP_STACK_ALIGNMENT + 1)
#define KHCI_TASK_TASK_STACK_SIZE (sizeof(TD_STRUCT) + 1200 + PSP_STACK_ALIGNMENT + 1)


#endif /* __task_template_list_h__ */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
