/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PTB0.c
**     Project     : ProcessorExpert
**     Processor   : MCF51JF128VLH
**     Component   : Init_IRQ
**     Version     : Component 01.001, Driver 01.01, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2012-11-19, 13:48, # CodeGen: 81
**     Abstract    :
**          This file implements the IRQ (IRQ) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : PTB0
**          Device                                         : IRQ
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Detection mode                               : Edge only
**            Edge select                                  : Falling or low
**            Pull device                                  : enabled
**          Pins                                           : 
**            External interrupt pin                       : Enabled
**              External interrupt pin                     : IRQ/PTB0/EZP_MS_b/I2C0_SCL/EZP_CS_b
**              External interrupt pin signal              : 
**          Interrupts                                     : 
**            Interrupt                                    : Virq
**            Interrupt request                            : Enabled
**            Interrupt priority                           : level 7, midpoint priority within level
**            Interrupt enable                             : yes
**            ISR name                                     : PTB0_interrupt
**          Initialization                                 : 
**            Pin enable                                   : yes
**            Call Init method                             : yes
**     Contents    :
**         Init - void PTB0_Init(void);
**
**     Copyright : 1997 - 2012 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE PTB0. */

#include "PTB0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  PTB0_Init (component Init_IRQ)
**
**     Description :
**         This method initializes registers of the IRQ module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PTB0_Init(void)
{
  /* SIM_SCGC4: IRQ=1 */
  SIM_SCGC4 |= (uint8_t)0x02U;                            
  /* IRQ_SC: ??=0,IRQPDD=0,IRQEDG=0,IRQPE=1,IRQF=0,IRQACK=1,IRQIE=1,IRQMOD=0 */
  IRQ_SC = (uint8_t)0x16U;                             
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      ProcessorExpert.c
**      Events.c
**
** ###################################################################
PE_ISR(PTB0_interrupt)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END PTB0. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.02]
**     for the Freescale ColdFirePlus series of microcontrollers.
**
** ###################################################################
*/
