/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PIT0.c
**     Project     : ProcessorExpert
**     Processor   : MK53DN512ZCLQ10
**     Component   : TimerInt
**     Version     : Component 02.160, Driver 01.01, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-01-28, 15:48, # CodeGen: 9
**     Abstract    :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings    :
**         Timer name                  : PIT_CVAL0 (32-bit)
**         Compare name                : PIT_LDVAL0
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-[driven by slave component]
**             Clock                   : [driven by slave component] Hz
**           Initial period/frequency
**             Xtal ticks              : ---
**             microseconds            : ---
**             milliseconds            : ---
**             seconds                 : ---
**             seconds (real)          : 125
**             Hz                      : ---
**             kHz                     : ---
**             MHz                     : ---
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : PIT_CVAL0 [0x40037104]
**              Mode                   : PIT_MCR   [0x40037000]
**              Run                    : PIT_TCTRL0 [0x40037108]
**
**         Compare registers
**              Compare                : PIT_LDVAL0 [0x40037100]
**
**         Flip-flop registers
**     Contents    :
**         Enable  - byte PIT0_Enable(void);
**         Disable - byte PIT0_Disable(void);
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE PIT0. */

#include "Events.h"
#include "PIT0.h"

/*
** ===================================================================
**     Method      :  PIT0_Enable (component TimerInt)
**
**     Description :
**         This method enables the component - it starts the timer.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte PIT0_Enable(void)

**  This method is implemented as a macro. See PIT0.h file.  **
*/

/*
** ===================================================================
**     Method      :  PIT0_Disable (component TimerInt)
**
**     Description :
**         This method disables the component - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte PIT0_Disable(void)

**  This method is implemented as a macro. See PIT0.h file.  **
*/

/*
** ===================================================================
**     Method      :  PIT0_OnInterrupt (component TimerInt)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void TimerIntLdd1_OnInterrupt(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  PIT0_OnInterrupt();                  /* Invoke OnInterrupt event */
}

/* END PIT0. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
