/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : usb_classes.h
**     Project   : ProcessorExpert
**     Processor : MK40N512MD100
**     Component : USB_HID_CLASS
**     Version   : Driver 01.00, CPU db: 3.00.003
**     Compiler  : CodeWarrior ARM C Compiler
**     Date/Time : 2012-11-19, 13:45, # CodeGen: 30
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/

#ifndef __usb_classes_h__
#define __usb_classes_h__

#endif
/* EOF */

